apiVersion : apps/v1
kind: Deployment
metadata:
  name: helm-web-deployment-3
  labels:
    app : helm-k8s-deployment-3
spec:
  replicas: 3
  selector:
    matchLabels:
      project: aws-helm-3
  template:
    metadata:
      labels:
        project: aws-helm-3   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : webserver-3
          image: sqlhub/1html:v2
          ports:
            - containerPort: 80