apiVersion: v1
kind: Service
metadata:
  name: lana-single-pod-service-2
  labels:
    env  : prod
    owner: lana
spec:
  selector:
    project: aws-helm-2    # Selecting PODS with those Labels
  ports:
    - name      : app-listener-2
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
  type: LoadBalancer